import { createFeatureSelector, createSelector } from '@ngrx/store';
import { UserState, userAdapter } from './user.state';

export const selectUserState = createFeatureSelector<UserState>('users'); // Adjust 'users' to your feature name

// Get the state of the users feature
const {
  selectIds,
  selectEntities,
  selectAll,
  selectTotal,
} = userAdapter.getSelectors(selectUserState);

export const selectAllUsers = createSelector(
  selectUserState,
  selectAll // Use the selectAll selector generated by the adapter
);

export const selectUserEntities = createSelector(
  selectUserState,
  selectEntities // Use the selectEntities selector generated by the adapter
);

export const selectCurrentUser = createSelector(
  selectUserState,
  (state) => {
    const user = state.entities[state.ids[0] as number];
    console.log('Current User from Selector:', user);
    return user ? user : null;
  }
);

export const selectUserToken = createSelector(
  selectUserState,
  (state) => state.token
);

export const selectUserLoading = createSelector(
  selectUserState,
  (state) => state.loading
);

export const selectUserError = createSelector(
  selectUserState,
  (state) => state.error
);

export const selectUserCourseIds = createSelector(
  selectUserState,
  (state) => state.entities[state.ids[0] as number]?.courseIds || []
);